//Host Env
export const HOST_ENV = "http://dorm-heroes-server.herokuapp.com";

// Create Issue Section
export const CREATE_NEW_ISSUE = "CREATE_NEW_ISSUE";
export const CREATE_NEW_ISSUE_RESPONSE = "CREATE_NEW_ISSUE_RESPONSE";
export const SET_ISSUE = "SET_ISSUE";

// Fetch disturbance type Section
export const FETCH_DISTURBANCE_TYPES_REQUEST =
  "FETCH_DISTURBANCE_TYPES_REQUEST";
export const FETCH_DISTURBANCE_TYPES_SUCCESS =
  "FETCH_DISTURBANCE_TYPES_SUCCESS";
export const FETCH_DISTURBANCE_TYPES_FAILURE =
  "FETCH_DISTURBANCE_TYPES_FAILURE";
export const SET_CURRENT_DISTURBANCE_TYPE = "SET_CURRENT_DISTURBANCE_TYPE";
export const INITIAL_STATE = "INITIAL_STATE";

// Get Issues Section
export const FETCH_ISSUES_REQUEST = "FETCH_ISSUES_REQUEST";
export const FETCH_ISSUES_SUCCESS = "FETCH_ISSUES_SUCCESS";
export const FETCH_ISSUES_FAILURE = "FETCH_ISSUES_FAILURE";
